### ISSUE TITLE
Can't compile with GCC 4.8.4 (Ubuntu 14.04 LTS)

### ISSUE THREAD

**Issue by homm** [ermig1979/Simd#7]
```
$ gcc -v
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

Output:
```
In file included from /home/homm/Code/pillow-perf/simd/src/Test/TestContour.cpp:312:0:
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp: In member function ‘void Simd::ContourDetector<A>::ContourAnchors(int, int)’:
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp:176:51: error: expected primary-expression before ‘>’ token
                 const uint8_t * a = &_a.At<uint8_t>(0, row);
                                                   ^
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp:180:50: error: expected primary-expression before ‘(’ token
                         _anchors.push_back(Anchor(Point(col, row), _m.At<int16_t>(col, row) / 2));
                                                  ^
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp:180:81: error: expected primary-expression before ‘>’ token
                         _anchors.push_back(Anchor(Point(col, row), _m.At<int16_t>(col, row) / 2));
                                                                                 ^
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp: In member function ‘void Simd::ContourDetector<A>::SmartRoute(Simd::ContourDetector<A>::Contours&, Simd::ContourDetector<A>::Contour&, ptrdiff_t, ptrdiff_t, size_t, uint16_t, Simd::ContourDetector<A>::Direction)’:
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp:215:38: error: expected primary-expression before ‘>’ token
                     if (_e.At<uint8_t>(x, y) == 0)
                                      ^
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp:217:38: error: expected primary-expression before ‘>’ token
                         _e.At<uint8_t>(x, y) = 255;
                                      ^
/home/homm/Code/pillow-perf/simd/prj/cmake/../../src/Simd/SimdContour.hpp:238:38: error: expected primary-expression before ‘>’ token
                     if (_e.At<uint8_t>(x, y) != 0)
                                      ^
```

And so on

**Comment by ermig1979** [comment]
I have fixed this bug.

**Comment by homm** [comment]
Thanks!
