### ISSUE TITLE
Debug build on Ubuntu 16.04 fails 

### ISSUE THREAD

**Issue by rashenoy** [ermig1979/Simd#70]
I am building the library for my host ubuntu 16.04 machine. Release build works. But Debug fails.
cmake . -DTOOLCHAIN="" -DTARGET="" -DCMAKE_BUILD_TYPE="Debug" 
It fails to build with following message

CMakeFiles/Simd.dir/build.make:5582: recipe for target 'CMakeFiles/Simd.dir/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwInterleave.cpp.o' failed
make[2]: *** [CMakeFiles/Simd.dir/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwInterleave.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Simd.dir/build.make:5654: recipe for target 'CMakeFiles/Simd.dir/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToBgr.cpp.o' failed
make[2]: *** [CMakeFiles/Simd.dir/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToBgr.cpp.o] Error 1
In file included from /home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToHue.cpp:26:0:
/home/rashenoy/Documents/Code/CppWorkspace/simd/prj/cmake-x86/../../src/Simd/SimdConversion.h: In function ‘__m512i Simd::Avx512bw::AdjustedYuvToRed16(__m512i, __m512i)’:
/home/rashenoy/Documents/Code/CppWorkspace/simd/prj/cmake-x86/../../src/Simd/SimdConversion.h:740:109: error: ‘_mm512_packs_epi32’ was not declared in this scope
                 AdjustedYuvToRed32(_mm512_unpackhi_epi16(y16, K16_0001), _mm512_unpackhi_epi16(v16, K_ZERO))));
                                                                                                             ^
/home/rashenoy/Documents/Code/CppWorkspace/simd/prj/cmake-x86/../../src/Simd/SimdConversion.h: In function ‘__m512i Simd::Avx512bw::AdjustedYuvToGreen16(__m512i, __m512i, __m512i)’:
/home/rashenoy/Documents/Code/CppWorkspace/simd/prj/cmake-x86/../../src/Simd/SimdConversion.h:753:108: error: ‘_mm512_packs_epi32’ was not declared in this scope
                 AdjustedYuvToGreen32(_mm512_unpackhi_epi16(y16, K16_0001), _mm512_unpackhi_epi16(u16, v16))));
                                                                                                            ^
/home/rashenoy/Documents/Code/CppWorkspace/simd/prj/cmake-x86/../../src/Simd/SimdConversion.h: In function ‘__m512i Simd::Avx512bw::AdjustedYuvToBlue16(__m512i, __m512i)’:
/home/rashenoy/Documents/Code/CppWorkspace/simd/prj/cmake-x86/../../src/Simd/SimdConversion.h:766:110: error: ‘_mm512_packs_epi32’ was not declared in this scope
                 AdjustedYuvToBlue32(_mm512_unpackhi_epi16(y16, K16_0001), _mm512_unpackhi_epi16(u16, K_ZERO))));
                                                                                                              ^
/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToHue.cpp: In function ‘__m512i Simd::Avx512bw::MulDiv16(const __m512i&, const __m512i&, const __m512&)’:
/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToHue.cpp:42:61: error: ‘_mm512_packs_epi32’ was not declared in this scope
             return _mm512_packs_epi32(quotientLo, quotientHi);
                                                             ^
CMakeFiles/Simd.dir/build.make:5702: recipe for target 'CMakeFiles/Simd.dir/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToHue.cpp.o' failed
make[2]: *** [CMakeFiles/Simd.dir/home/rashenoy/Documents/Code/CppWorkspace/simd/src/Simd/SimdAvx512bwYuvToHue.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/Simd.dir/all' failed
make[1]: *** [CMakeFiles/Simd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I tried to in the CMakeCache.txt
//AVX512 enable
AVX512:BOOL=OFF

but same result.

**Comment by ermig1979** [comment]
Hello. I can't reproduce the bug. So I need more information. What compiler (and it version) are you use to build Simd Library?

**Comment by rashenoy** [comment]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by ermig1979** [comment]
Perhaps GCC 5.4.0 does not support AVX-512BW extension.  I use 5.5.0 and it builds the library fine. You can use option -DAVX512=0 to disable this extension.
I will add to cmake checking for minimal compiler version.
